const SupportedLanguages: SupportedLanguages = {
  zh: 'Chinese 🇨🇳',
  es: 'Spanish 🇪🇸',
  en: 'English 🇺🇸',
  hi: 'Hindi 🇮🇳',
  ar: 'Arabic 🇸🇦',
  pt: 'Portuguese 🇵🇹',
  br: 'Brazilian Portuguese 🇧🇷',
  ru: 'Russian 🇷🇺',
  ja: 'Japanese 🇯🇵',
  pa: 'Punjabi 🇮🇳',
  de: 'German 🇩🇪',
  jv: 'Javanese 🇮🇩',
  id: 'Indonesian 🇮🇩',
  te: 'Telugu 🇮🇳',
  vi: 'Vietnamese 🇻🇳',
  ko: 'Korean 🇰🇷',
  fr: 'French 🇫🇷',
  mr: 'Marathi 🇮🇳',
  ta: 'Tamil 🇮🇳',
  tr: 'Turkish 🇹🇷',
  it: 'Italian 🇮🇹',
  fa: 'Persian 🇮🇷',
  ur: 'Urdu 🇵🇰',
  uk: 'Ukrainian 🇺🇦',
  gu: 'Gujarati 🇮🇳',
  pl: 'Polish 🇵🇱',
  ro: 'Romanian 🇷🇴',
  nl: 'Dutch 🇳🇱',
  el: 'Greek 🇬🇷',
  sv: 'Swedish 🇸🇪',
  hu: 'Hungarian 🇭🇺',
  fi: 'Finnish 🇫🇮',
  my: 'Burmese 🇲🇲',
  th: 'Thai 🇹🇭',
  ca: 'Catalan 🇪🇸',
  he: 'Hebrew 🇮🇱',
  am: 'Amharic 🇪🇹',
  lt: 'Lithuanian 🇱🇹',
  sk: 'Slovak 🇸🇰',
};

export default SupportedLanguages;
